### ISSUE TITLE
Error when executing areas_of_code study

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-sirmordred#100]
When running master/HEAD of all the tools, and launching mordred, after a while I see the following error:

```
2018-03-07 22:07:24,248 - grimoire_elk.arthur - ERROR - Problem executing study <bound method GitEnrich.enrich_areas_of_code of <grimoire_elk.elk.git.GitEnrich object at 0x7f68fb4a0940>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/arthur.py", line 479, in do_studies
    study(enrich_backend, no_incremental)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk/git.py", line 748, in enrich_areas_of_code
    areas_of_code(git_enrich=enrich_backend, in_conn=in_conn, out_conn=out_conn)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk/study_ceres_aoc.py", line 194, in areas_of_code
    ndocs = aoc.analyze()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk/ceres_base.py", line 80, in analyze
    from_date = self._out.latest_date()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk/ceres_base.py", line 264, in latest_date
    raise nfe
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk/ceres_base.py", line 252, in latest_date
    response = search.execute()
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch_dsl/search.py", line 679, in execute
    **self._params
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 636, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 163, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.NotFoundError: TransportError(404, 'index_not_found_exception', 'no such index')
```

The dashboard seems to be generated correctly, though. Any idea of what's happening? Just in case it matters, I'm testing this with Elasticsearch 6.1.

**Comment by acs** [comment]
Already fixed in master with the new approach for configuring studies.
