### ISSUE TITLE
keyError: 'assignee_data'

### ISSUE THREAD

**Issue by olblak** [chaoss/grimoirelab-sirmordred#135]
I am getting this error with mordred 'bitergia/mordred:18.04-01'

2018-04-13 07:45:52,128 - grimoire_elk.elk - ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 583, in enrich_backend
    total_ids = load_identities(ocean_backend, enrich_backend)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/elk.py", line 380, in load_identities
    identities = enrich_backend.get_identities(item)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/enriched/github.py", line 134, in get_identities
    user = self.get_sh_identity(item[identity + "_data"])
KeyError: 'assignee_data'

**Comment by acs** [comment]
@olblak could you share the github repository in which you are having the problem? If you are using mordred and you can share the config and projects data, I will try to reproduce it and create a fix.

**Comment by valeriocos** [comment]
Errors seem to be gone, no traces in PRD environment logs
