### ISSUE TITLE
Mordred require manuscripts to be installed

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-sirmordred#138]
I have updated the `grimoire-mordred` Python package and now, when I run `mordred -c mordred.cfg`, I get this error message:
```
$ mordred -c mordred-ubuconeu.cfg 
Traceback (most recent call last):
  File "/home/jsmanrique/grimoirelab/venv/bin/mordred", line 39, in <module>
    from mordred.mordred import Mordred
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/mordred/mordred.py", line 52, in <module>
    from mordred.task_report import TaskReport
  File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/mordred/task_report.py", line 35, in <module>
    from manuscripts.report import Report
ImportError: No module named 'manuscripts'
```
 Why?

And if `manuscripts` Python package is needed, is it not installed through `pip install --upgrade grimoire-mordred` ??

**Comment by acs** [comment]
@jgbarah is working on it AFAIK.

**Comment by valeriocos** [comment]
This should be fixed since we don't have this error in PRD environments. Furthermore, there is a PR: https://github.com/chaoss/grimoirelab-sirmordred/pull/349 that aims at removing the dependency with manuscript
