### ISSUE TITLE
Issue running areas of code study

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-sirmordred#149]
From https://github.com/chaoss/grimoirelab-elk/issues/349

In the original issue you can find more details on installed packages and tests done to try to reproduce it from https://github.com/chaoss/grimoirelab-elk.

@jsmanrique wrote:

> I am getting the following error running an `areas of code` analysis:

```
Executing for git the studies ['enrich_demography', 'enrich_areas_of_code']
/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/pandas/core/ops.py:816: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
 result = getattr(x, name)(y)
2018-05-11 07:46:03,905 - grimoire_elk.elk - ERROR - Problem executing study <bound method GitEnrich.enrich_areas_of_code of <grimoire_elk.enriched.git.GitEnrich object at 0x7f0f6ccf9c18>>
Traceback (most recent call last):
 File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/elk.py", line 460, in do_studies
   study(enrich_backend, no_incremental)
 File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/enriched/git.py", line 787, in enrich_areas_of_code
   areas_of_code(git_enrich=enrich_backend, in_conn=in_conn, out_conn=out_conn)
 File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/enriched/study_ceres_aoc.py", line 194, in areas_of_code
   ndocs = aoc.analyze()
 File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/enriched/ceres_base.py", line 93, in analyze
   process_results = self.process(item_block)
 File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/grimoire_elk/enriched/study_ceres_aoc.py", line 158, in process
   events_df = data_filtered.filter_(["filepath"], "-")
 File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/cereslib/dfutils/filter.py", line 71, in filter_
   self.data = self.data[self.data[column] != value]
 File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/pandas/core/ops.py", line 879, in wrapper
   res = na_op(values, other)
 File "/home/jsmanrique/grimoirelab/venv/lib/python3.5/site-packages/pandas/core/ops.py", line 818, in na_op
   raise TypeError("invalid type comparison")
TypeError: invalid type comparison
```
>
>Config files:
>* [projects.json.txt](https://github.com/chaoss/grimoirelab-elk/files/1995372/projects.json.txt)
>
>My `mordred.cfg` file:
```
[general]
short_name = Project_Name
update = false
min_update_delay = 10
debug = true
logs_dir = /tmp/logs

[projects]
projects_file = projects.json

[es_collection]
url = http://localhost:9200
user =
password =

[es_enrichment]
url = http://127.0.0.1:9200
user =
password =
autorefresh = true

[sortinghat]
host = localhost
user = root
password = *******************
database = shdb
load_orgs = true
orgs_file = orgs.json
unaffiliated_group = Unknown
affiliate = true
autoprofile = [github,git]
matching = [email-name]
sleep_for = 0
#bots_names = []

[panels]
kibiter_time_from= "now-90d"
kibiter_default_index= "git"

[phases]
collection = true
identities = true
enrichment = true
panels = true

[git]
raw_index = git-gathered-raw
enriched_index = git-gathered
studies = [enrich_demography, enrich_areas_of_code]

[github]
raw_index = github-gathered-raw
enriched_index = github-gathered
api-token = **************************************************
sleep-for-rate = true
sleep-time = 300
no-archive = true

[*pipermail]
raw_index = mls-gathered-raw
enriched_index = mls-gathered

[*meetup]
raw_index = meetup-gathered-raw
enriched_index = meetup-gathered
api-token = *****************************************
sleep-for-rate = true
no-archive = true

[*stackexchange]
raw_index = stackexchange-gathered-raw
enriched_index = stackexchange-gathered
api-token = *************************************
```

**Comment by valeriocos** [comment]
There are no trace in the logs produced by the PRD environments, it was probably fixed time ago
