### ISSUE TITLE
[studies] Error in configuration file

### ISSUE THREAD

**Issue by jgbarah** [chaoss/grimoirelab-sirmordred#156]
The following configuration for studies raises an error when running Mordred (see below):

```
studies = []

[enrich_demography]

[enrich_areas_of_code]

```

The error is raised after retrieval of git data is done:

```
Enrichment for git: starting...
2018-06-04 15:29:09,565 - mordred.task_enrich - ERROR - Missing config for study :
2018-06-04 15:29:09,565 - mordred.task_manager - ERROR - Exception in Task Manager Missing config for study :
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_manager.py", line 92, in run
    task.execute()
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 291, in execute
    raise e
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 281, in execute
    self.__enrich_items()
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 126, in __enrich_items
    studies_args = self.__load_studies()
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 73, in __load_studies
    raise DataEnrichmentError(msg)
mordred.error.DataEnrichmentError: Missing config for study :
Exception in thread git:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_manager.py", line 92, in run
    task.execute()
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 291, in execute
    raise e
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 281, in execute
    self.__enrich_items()
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 126, in __enrich_items
    studies_args = self.__load_studies()
  File "/usr/local/lib/python3.5/dist-packages/mordred/task_enrich.py", line 73, in __load_studies
    raise DataEnrichmentError(msg)
mordred.error.DataEnrichmentError: Missing config for study :
```

This with 18.05-03.

Maybe this could be related to #155?

**Comment by jgbarah** [comment]
Closed via #157
