### ISSUE TITLE
Passwords with "special" chars don't seem to work

### ISSUE THREAD

**Issue by markwalkom** [chaoss/grimoirelab-sirmordred#233]
I'm trying to send things to a hosted Elasticsearch instance by defining this in `infra.cfg` and then passing that to the `full` container at run time.

Here's the config;
```
[es_collection]
url = https://hiddenidentifier.us-central1.gcp.cloud.es.io:9243
user = user
password = '11$abc123&%asdf'

[es_enrichment]
url = https://hiddenidentifier.us-central1.gcp.cloud.es.io:9243
user = user
password = '11$abc123&%asdf'
```

Here's where I run it and the resulting failure;
```
mark@bender:~/Workspace/docker/grimoirelab$ docker run -p 127.0.0.1:5601:5601 -v $(pwd)/credentials.cfg:/override.cfg -v $(pwd)/infra.cfg:/infra.cfg -v $(pwd)/logs:/logs -v $(pwd)/es-data:/var/lib/elasticsearch -v $(pwd)/projects.json:/projects.json -t grimoirelab/full
Starting container: 1f6ee6d09472
Starting Elasticsearch
[ ok ] Starting Elasticsearch Server:.
Waiting for Elasticsearch to start...
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      -
Elasticsearch started
Starting MariaDB
[ ok ] Starting MariaDB database server: mysqld . . ..
Waiting for MariaDB to start...
tcp6       0      0 :::3306                 :::*                    LISTEN      -
MariaDB started
Starting Kibiter
Waiting for Kibiter to start...
........Kibiter started
Starting SirMordred to build a GrimoireLab dashboard
This will usually take a while...
Traceback (most recent call last):
  File "/usr/local/bin/sirmordred", line 144, in <module>
    config = Config(args.config_files[0], args.config_files[1:])
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/config.py", line 56, in __init__
    self.__read_conf_files()
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/config.py", line 769, in __read_conf_files
    raw_conf = {s: dict(parser.items(s)) for s in parser.sections()}
  File "/usr/local/lib/python3.5/dist-packages/sirmordred/config.py", line 769, in <dictcomp>
    raw_conf = {s: dict(parser.items(s)) for s in parser.sections()}
  File "/usr/lib/python3.5/configparser.py", line 855, in items
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.5/configparser.py", line 855, in <listcomp>
    return [(option, value_getter(option)) for option in d.keys()]
  File "/usr/lib/python3.5/configparser.py", line 852, in <lambda>
    section, option, d[option], d)
  File "/usr/lib/python3.5/configparser.py", line 393, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib/python3.5/configparser.py", line 443, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%asdf"'
Failed to start SirMordred: 1
```

I've tried single and double quotes but it doesn't seem to make a difference, I get the same error.

**Comment by sduenas** [comment]
Have you tried with double `%%`? As these values are read as python strings and `%` character is used to format strings, it has to be escaped using double `%%`.

**Comment by markwalkom** [comment]
That appears to work, it doesn't error on the same thing. But it does produce;
```
Starting SirMordred to build a GrimoireLab dashboard
This will usually take a while...
Error while consuming configuration:  ('Missing section param:', 'sortinghat', 'user')
Failed to start SirMordred: 1
```

And if I check the logs it shows it's still using a local instance;
```
2018-10-19 00:34:21,161 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): localhost:9200
2018-10-19 00:34:21,471 - urllib3.connectionpool - DEBUG - http://localhost:9200 "GET / HTTP/1.1" 200 275
2018-10-19 00:34:21,561 - urllib3.connectionpool - DEBUG - http://localhost:9200 "GET / HTTP/1.1" 200 275
```

Should I be passing this into the `override.cfg` rather than `infra.cfg`?

**Comment by sduenas** [comment]
As I can see in that error on the output, you don't have configured the parameters for sortinghat.

See: https://github.com/chaoss/grimoirelab-sirmordred/blob/master/utils/setup.cfg#L40

**Comment by valeriocos** [comment]
Sorry for the late reply @markwalkom . If I'm not wrong, Sortinghat configuration should go to credentials.cfg (https://chaoss.github.io/grimoirelab-tutorial/sirmordred/container.html#running-grimoirelabinstalled). We are improving the documentation and we will keep your question into account in the new version.

If you have specific question about GrimoireLab, you may be interested in joining the weekly calls (all Tuesdays from 17h to 18h, Madrid time, on zoom: https://unomaha.zoom.us/j/720431288).The notes of the previous meetings are available at: https://docs.google.com/document/d/19CNl6J0YqVrRKFy1SuSybiKaWIY8yGkrMbuzJ3q8f_s

Thanks and sorry again for the late reply
