### ISSUE TITLE
Error: grimoire_elk.elastic - ERROR - Error creating ES mappings

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-sirmordred#318]
Running sirmordred gives the following ES error, any ideas what should I do?
```
2019-08-05 10:55:51,320 - grimoire_elk.elastic - ERROR - Error creating ES mappings {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}
2019-08-05 10:55:51,320 - grimoire_elk.elastic - ERROR - Mapping: 
         {
            "dynamic":true,
            "properties": {
                "data": {
                    "properties": {
                        "message": {
                            "type": "text",
                            "index": true
                        }
                    }
                }
            }
        }
        
2019-08-05 10:55:51,321 - sirmordred.task_manager - ERROR - [thread:140384777778944][git] Exception in Task Manager 400 Client Error: Bad Request for url: http://elasticsearch-master.dev-analytics-elasticsearch:9200/git_raw_xenel-mihug-bukyd-nekir-zysym-rediv-zotiz-soteb-haneh-hetym-kaxox/items/_mapping
Traceback (most recent call last):
  File "/repos/grimoirelab-sirmordred/sirmordred/task_manager.py", line 98, in run
    task.execute()
  File "/repos/grimoirelab-sirmordred/sirmordred/task_collection.py", line 438, in execute
    collect_arthur_items(repo)
  File "/repos/grimoirelab-sirmordred/sirmordred/task_collection.py", line 389, in collect_arthur_items
    elastic_ocean = get_elastic(es_col_url, es_index, clean, ocean_backend)
  File "/repos/grimoirelab-elk/grimoire_elk/utils.py", line 252, in get_elastic
    analyzers=analyzers, aliases=es_aliases)
  File "/repos/grimoirelab-elk/grimoire_elk/elastic.py", line 101, in __init__
    self.create_mappings(map_dict)
  File "/repos/grimoirelab-elk/grimoire_elk/elastic.py", line 323, in create_mappings
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://elasticsearch-master.dev-analytics-elasticsearch:9200/git_raw_xenel-mihug-bukyd-nekir-zysym-rediv-zotiz-soteb-haneh-hetym-kaxox/items/_mapping
Exception in thread git:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/repos/grimoirelab-sirmordred/sirmordred/task_manager.py", line 98, in run
    task.execute()
  File "/repos/grimoirelab-sirmordred/sirmordred/task_collection.py", line 438, in execute
    collect_arthur_items(repo)
  File "/repos/grimoirelab-sirmordred/sirmordred/task_collection.py", line 389, in collect_arthur_items
    elastic_ocean = get_elastic(es_col_url, es_index, clean, ocean_backend)
  File "/repos/grimoirelab-elk/grimoire_elk/utils.py", line 252, in get_elastic
    analyzers=analyzers, aliases=es_aliases)
  File "/repos/grimoirelab-elk/grimoire_elk/elastic.py", line 101, in __init__
    self.create_mappings(map_dict)
  File "/repos/grimoirelab-elk/grimoire_elk/elastic.py", line 323, in create_mappings
    res.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://elasticsearch-master.dev-analytics-elasticsearch:9200/git_raw_xenel-mihug-bukyd-nekir-zysym-rediv-zotiz-soteb-haneh-hetym-kaxox/items/_mapping
```
- SirMordred - master branch, newest.
- ElasticSearch:
```
{
  "name" : "elasticsearch-master-0",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "iYkoYqCWRLiOB1wzsfSFoQ",
  "version" : {
    "number" : "7.2.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "508c38a",
    "build_date" : "2019-06-20T15:54:18.811730Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
pod "curl-test-es" deleted.
```

**Comment by lukaszgryglicki** [comment]
cc @valeriocos this [issue](https://github.com/chaoss/grimoirelab-elk/issues/156) is a bit similar.Any suggestions?

**Comment by lukaszgryglicki** [comment]
Is ElasticSearch 6.8.0 supported by the grimoire stack? Maybe I should install some other/specific version to run ELK stack from SirMordred?

**Comment by lukaszgryglicki** [comment]
[This](https://techoverflow.net/2019/05/02/how-to-fix-elasticsearch-types-cannot-be-provided-in-put-mapping-requests-unless-the-include_type_name-parameter-is-set-to-true/) may be a suggestion how to fix that in `grimoirelab-elk/grimoire_elk/elastic.py` somewhere around line 323, but I'm not a python guy and I'm not sure. I will try this anyway tomorrow unless somebody finds a solution by then.

**Comment by lukaszgryglicki** [comment]
Fixed. This is due to ES version `7.x`. Grimoire stack doesn't seem to support it.

**Comment by GeorgLink** [comment]
Thanks @lukaszgryglicki 

I just wanted to drop in and let you know that I appreciate your bug hunting.
Maintainers are currently on vacation.

**Comment by jsmanrique** [comment]
I think this is a GrimoireELK issue, not a Mordred one: chaoss/grimoirelab-elk#711
