### ISSUE TITLE
Github 403 Issues errors

### ISSUE THREAD

**Issue by Wirick** [chaoss/grimoirelab-sirmordred#497]
Hello, just trying out the grimoirelab product and I'm finding that I'm having 403 errors specifically when trying to read github issues with the github2 and the githubql backends. URL: https://api.github.com/repos/Unity-Technologies/obstacle-tower-env/issues?state=all&per_page=100&direction=asc&sort=updated. Error:
```bash
mordred 2020-12-21 22:43:40 ERROR    Error feeding raw from githubql (https://github.com/Unity-Technologies/obstacle-tower-env): HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Unity-Technologies/obstacle-tower-env/issues?state=all&per_page=100&direction=asc&sort=updated (Caused by ResponseError('too many 403 error responses')) -mordred-collection-5cbdf66959-52khl mordred Traceback (most recent call last):
mordred   File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
mordred     timeout=timeout
mordred   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 731, in urlopen
mordred     body_pos=body_pos, **response_kw)
mordred   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 731, in urlopen
mordred     body_pos=body_pos, **response_kw)
mordred   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 731, in urlopen
mordred     body_pos=body_pos, **response_kw)
mordred   [Previous line repeated 2 more times]
mordred   File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 711, in urlopen
mordred     retries = retries.increment(method, url, response=response, _pool=self)
mordred   File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 399, in increment
mordred     raise MaxRetryError(_pool, url, error or ResponseError(cause))
mordred urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Unity-Technologies/obstacle-tower-env/issues?state=all&per_page=100&direction=asc&sort=updated (Caused by ResponseError('too many 403 error responses'))
mordred
mordred During handling of the above exception, another exception occurred:
mordred
mordred Traceback (most recent call last):
mordred   File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/elk.py", line 162, in feed_backend
mordred     ocean_backend.feed(**params)
mordred   File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/raw/elastic.py", line 228, in feed
mordred     self.feed_items(items)
mordred   File "/usr/local/lib/python3.7/dist-packages/grimoire_elk/raw/elastic.py", line 244, in feed_items
mordred     for item in items:
mordred   File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 226, in fetch
mordred     for item in self.fetch_items(category, **kwargs):
mordred   File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/githubql.py", line 394, in __fetch_events
mordred     for raw_issues in issues_groups:
mordred   File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 882, in fetch_items
mordred     response = self.fetch(url_next, payload=payload)
mordred   File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 864, in fetch
mordred     response = super().fetch(url, payload, headers, method, stream, auth)
mordred   File "/usr/local/lib/python3.7/dist-packages/perceval/client.py", line 143, in fetch
mordred     response = self._fetch_from_remote(url, payload, headers, method, stream, auth)
mordred   File "/usr/local/lib/python3.7/dist-packages/perceval/client.py", line 175, in _fetch_from_remote
mordred     verify=self.ssl_verify, auth=auth)
mordred   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 546, in get
mordred     return self.request('GET', url, **kwargs)
mordred   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 533, in request
mordred     resp = self.send(prep, **send_kwargs)
mordred   File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 646, in send
mordred     r = adapter.send(request, **kwargs)
mordred   File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 507, in send
mordred     raise RetryError(e, request=request)
mordred requests.exceptions.RetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Unity-Technologies/obstacle-tower-env/issues?state=all&per_page=100&direction=asc&sort=updated (Caused by ResponseError('too many 403 error responses'))
```

I've already started using a token, which cleared up the rate limit errors that I was seeing.

Images:
```
  mariadb:10.0',
  hatstall:latest',
  elasticsearch:6.8.6-secured',
  kibiterImage:: kibiter:secured-v6.8.6-3',
  mordredImage:: mordred/mordred:0.2.52',
```

Wondering if this has something to do if a repo went from private -> public, but not sure, any tips appreciated. I can see the github api url when I am logged in and also not logged into github, so not sure that this is the problem

**Comment by zhquan** [comment]
Hi @Wirick,

Could you share your `setup.cfg` file?

Make sure that the parameter `sleep_for_rate` is activated.
```
[githubql]
api-token = <your-token>
raw_index = githubql_raw
enriched_index = githubql_enriched
sleep-for-rate = true
no-archive = true
```

> Wondering if this has something to do if a repo went from private -> public, but not sure, any tips appreciated. I can see the github api url when I am logged in and also not logged into github, so not sure that this is the problem

If the repo is public you can see the GitHub API URL even if you are not logged in.

Best,
Quan

**Comment by Wirick** [comment]
Here are the blocks in my config:
```bash
      [githubql]
      api-token = <MY_TOKEN>
      raw_index = github_event_raw
      enriched_index = github_event_enriched
      sleep-for-rate = true
      sleep-time = "300"
      no-archive = true
      studies = [enrich_reference_analysis]

      [enrich_reference_analysis]

      [github2:issue]
      api-token = <MY_TOKEN>
      raw_index = github2-issues_raw
      enriched_index = github2-issues_enriched
      sleep-for-rate = true
      category = issue
      no-archive = true
      studies = [enrich_geolocation:user_issue2, enrich_geolocation:assignee_issue2]

      [enrich_geolocation:user_issue2]
      location_field = user_location
      geolocation_field = user_geolocation

      [enrich_geolocation:assignee_issue2]
      location_field = assignee_location
      geolocation_field = assignee_geolocation
```

**Comment by zhquan** [comment]
Hi @Wirick,

I cannot reproduce the error. Could you execute with [perceval](https://github.com/chaoss/grimoirelab-perceval) to make sure that your token is correct?

I can fetch all items with perceval and mordred.
```
$ perceval githubql Unity-Technologies obstacle-tower-env -t <token> > /dev/null
[2020-12-23 12:14:48,748] - Sir Perceval is on his quest.
[2020-12-23 12:15:47,668] - Summary of results

	   Total items: 	214
	Items produced: 	214
	 Items skipped: 	0

	Last item UUID: 	dcb4517e8d0fb1a63d4deae8dc1847ca4772db2c
	Last item date: 	2019-02-14 19:58:05+00:00

	Min. item date: 	2019-01-17 19:03:00+00:00
	Max. item date: 	2020-09-28 03:58:05+00:00

	Min. offset: 	-	Max. offset: 	-	Last offset: 	-


[2020-12-23 12:15:47,670] - Sir Perceval completed his quest.

Process finished with exit code 0

```

Best,
Quan

**Comment by Wirick** [comment]
aha. So I figured this out. but it actually has to do with me using a personal access token instead of authenticating with a robot account, i.e. needs this issue https://github.com/chaoss/grimoirelab-perceval/issues/706 to be resolved because my org wants me to sso in the api request

**Comment by sduenas** [comment]
@Wirick I use personal tokens with perceval and everything works fine. How are you running the platform? With the grimoirelab docker image? What version?

**Comment by Wirick** [comment]
@sduenas this is running in k8s running the docker images in containers (version 0.52.2) as I referenced at the beginning of the pr. I checked the scope of my token against a public repo outside of my organization:
```
bitergia@grimoirelab-sirmordred-collection-858b49c66f-fntbd:~$ curl -H "Authorization: token MY_TOKEN" https://api.github.com/repos/google/jsonnet/issues -I
HTTP/1.1 200 OK
Server: GitHub.com
Date: Wed, 23 Dec 2020 15:11:17 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 99510
Status: 200 OK
Cache-Control: private, max-age=60, s-maxage=60
Vary: Accept, Authorization, Cookie, X-GitHub-OTP
ETag: ETag
X-OAuth-Scopes: public_repo
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3; format=json
Link: <https://api.github.com/repositories/22527161/issues?page=2>; rel="next", <https://api.github.com/repositories/22527161/issues?page=6>; rel="last"
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4994
X-RateLimit-Reset: 1608739666
X-RateLimit-Used: 6
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: REQ_ID
```
But since I'm a member of Unity org, when I try to do the same for one of the public repos I'm denied because it wants sso for my personal token. This is why I referenced perveval issue 706
```
bitergia@grimoirelab-sirmordred-collection-858b49c66f-fntbd:~$ curl -H "Authorization: token MY_TOKEN" https://api.github.com/repos/Unity-Technologies/obstacle-tower-env/issues -I
HTTP/1.1 403 Forbidden
Server: GitHub.com
Date: Wed, 23 Dec 2020 15:11:31 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 268
Status: 403 Forbidden
X-GitHub-SSO: required; url=https://<MY_ORG_SSO>
X-OAuth-Scopes: public_repo
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3; format=json
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4993
X-RateLimit-Reset: 1608739666
X-RateLimit-Used: 7
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: MY_REQUEST_ID
```

**Comment by sduenas** [comment]
I've been testing it with perceval and it works without problems. Can you test it too? You can run inside the container the next command:

```
perceval githubql -t "MY_TOKEN" -- "Unity-Technologies" "obstacle-tower-env"
```

**Comment by Wirick** [comment]
Hi @sduenas here is the command you requested, as well as confirmation that my token is authorized for public repos and is not rate limited. The problem is that Unity has sso, and I'm a member of the org, so github is trying to sso my token, even though it only has public repo scope. You could maybe this is a bug in github, but also, this is why we want to do an app rather than a personal access token :) 

```bash
╰─ kubectl -n team-demo exec -it grimoirelab-sirmordred-collection bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
bitergia@grimoirelab-sirmordred-collection-58cdb89b6f-5sf7q:~$ curl -H "Authorization: token <MY_TOKEN>" https://api.github.com/repos/google/jsonnet/issues -I
HTTP/1.1 200 OK
Server: GitHub.com
Date: Wed, 30 Dec 2020 11:35:17 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 100049
Status: 200 OK
Cache-Control: private, max-age=60, s-maxage=60
Vary: Accept, Authorization, Cookie, X-GitHub-OTP
X-OAuth-Scopes: public_repo
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3; format=json
Link: <https://api.github.com/repositories/22527161/issues?page=2>; rel="next", <https://api.github.com/repositories/22527161/issues?page=6>; rel="last"
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4999
X-RateLimit-Reset: 1609331717
X-RateLimit-Used: 1
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: 912A:7F68:8620A5:19FD379:5FEC65F5

bitergia@grimoirelab-sirmordred-collection:~$ curl -H "Authorization: token <MY TOKEN>" https://api.github.com/repos/Unity-Technologies/obstacle-tower-env/issues -I
HTTP/1.1 403 Forbidden
Server: GitHub.com
Date: Wed, 30 Dec 2020 11:35:57 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 268
Status: 403 Forbidden
X-GitHub-SSO: required; url=https://github.com/orgs/Unity-Technologies/sso?authorization_request=ABIUHQ746DAEEPJQCF3VGL275R2C3A5PN5ZGOYLONF5GC5DJN5XF62LEZYAANAGUVVRXEZLEMVXHI2LBNRPWSZGOEAZIIT5PMNZGKZDFNZ2GSYLML52HS4DFVNHWC5LUNBAWGY3FONZQ
X-OAuth-Scopes: public_repo
X-Accepted-OAuth-Scopes: repo
X-GitHub-Media-Type: github.v3; format=json
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4998
X-RateLimit-Reset: 1609331717
X-RateLimit-Used: 2
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
Access-Control-Allow-Origin: *
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Content-Security-Policy: default-src 'none'
Vary: Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: 91E0:2056:5AD5952:D1F115D:5FEC661D

bitergia@grimoirelab-sirmordred-collection:~$ perceval githubql -t "<MY_TOKEN>" -- "Unity-Technologies" "obstacle-tower-env"
[2020-12-30 11:36:37,822] - Sir Perceval is on his quest.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 731, in urlopen
    body_pos=body_pos, **response_kw)
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.7/dist-packages/urllib3/connectionpool.py", line 711, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/local/lib/python3.7/dist-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Unity-Technologies/obstacle-tower-env/issues?state=all&per_page=100&direction=asc&sort=updated (Caused by ResponseError('too many 403 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 618, in run
    for item in big.items:
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 794, in __fetch
    raise e
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 788, in __fetch
    for item in items:
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 226, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/githubql.py", line 394, in __fetch_events
    for raw_issues in issues_groups:
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 882, in fetch_items
    response = self.fetch(url_next, payload=payload)
  File "/usr/local/lib/python3.7/dist-packages/perceval/backends/core/github.py", line 864, in fetch
    response = super().fetch(url, payload, headers, method, stream, auth)
  File "/usr/local/lib/python3.7/dist-packages/perceval/client.py", line 143, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, auth)
  File "/usr/local/lib/python3.7/dist-packages/perceval/client.py", line 175, in _fetch_from_remote
    verify=self.ssl_verify, auth=auth)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Unity-Technologies/obstacle-tower-env/issues?state=all&per_page=100&direction=asc&sort=updated (Caused by ResponseError('too many 403 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perceval", line 169, in <module>
    main()
  File "/usr/local/bin/perceval", line 115, in main
    cmd.run()
  File "/usr/local/lib/python3.7/dist-packages/perceval/backend.py", line 628, in run
    raise RuntimeError(str(e))
RuntimeError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/Unity-Technologies/obstacle-tower-env/issues?state=all&per_page=100&direction=asc&sort=updated (Caused by ResponseError('too many 403 error responses'))
```

**Comment by jjmerchante** [comment]
GitHub apps are supported as described at https://github.com/chaoss/grimoirelab-perceval/issues/706,
