### ISSUE TITLE
[doc] Error feeding raw from cocom while running `micro.py`

### ISSUE THREAD

**Issue by TieWay59** [chaoss/grimoirelab-sirmordred#539]
### Digest

I'm following tutorial of [Source code and docker](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#source-code-and-docker-) from [grimoirelab-sirmordred/Getting-Started.md](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md).

While running the first `micro.py` command: 

https://github.com/chaoss/grimoirelab-sirmordred/blob/8a8bb8de7e914b60bdfcbf0c074fda345236c7b2/Getting-Started.md?plain=1#L188

It logs out that `Error feeding raw from cocom (https://github.com/chaoss/grimoirelab-toolkit): Impossible to checkout the worktree /tmp/worktrees/grimoirelab-toolkit-git at 9dc821962567715e5358b1192e1b15d8868d2b6c` (I'll display the full log in following section).

As @vchrombie suggests, I just remove the `cocom` backend (see the command above) and leave only `git`, and this workaround this error fine. And actually, this error doesn't affect the demo result.

**UPD on 8 days later**: According @zhquan points out, `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/worktrees/grimoirelab-toolkit-git': '/tmp/worktrees/grimoirelab-toolkit-git'` implies this issue is related to the directory not found, this folder can be created manually and leave it empty, and also I have to install `cloc` in my local machine.

### Detailed error log

```shell
$ micro.py --raw --enrich --cfg ./setup.cfg --backends git cocom

  2022-04-13 20:52:56,137 Reading projects data from  ./projects.json 
  2022-04-13 20:52:56,137 [git] collection phase starts
  2022-04-13 20:52:56,138 [git] collection starts for https://github.com/chaoss/grimoirelab-perceval
Collection for git: starting...
  2022-04-13 20:52:56,549 [git] Incremental from: 2022-04-01 07:02:38+00:00 for https://github.com/chaoss/grimoirelab-perceval
  2022-04-13 20:52:56,549 Fetching latest commits: 'https://github.com/chaoss/grimoirelab-perceval' git repository
  2022-04-13 20:52:58,854 Fetch process completed: 0 commits fetched
  2022-04-13 20:52:58,854 [git] Done collection for https://github.com/chaoss/grimoirelab-perceval
  2022-04-13 20:52:58,856 [git] collection finished for https://github.com/chaoss/grimoirelab-perceval
  2022-04-13 20:52:58,856 [git] collection phase finished in 00:00:02
Collection for git: finished after 00:00:02 hours
Collection for cocom: starting...
  2022-04-13 20:52:58,897 Loading raw data finished!
  2022-04-13 20:52:58,897 Reading projects data from  ./projects.json 
  2022-04-13 20:52:58,898 [cocom] collection phase starts
  2022-04-13 20:52:58,898 [cocom] collection starts for https://github.com/chaoss/grimoirelab-toolkit
  2022-04-13 20:52:58,946 [cocom] Incremental from: None for https://github.com/chaoss/grimoirelab-toolkit
  2022-04-13 20:52:58,952 Fetching commits: 'https://github.com/chaoss/grimoirelab-toolkit' git repository from 1970-01-01 00:00:00+00:00 to 2100-01-01 00:00:00+00:00; master branches

# --- begin ---

  2022-04-13 20:52:59,770 Analysis failed at 9dc821962567715e5358b1192e1b15d8868d2b6c
  2022-04-13 20:52:59,770 Error feeding raw from cocom (https://github.com/chaoss/grimoirelab-toolkit): Impossible to checkout the worktree /tmp/worktrees/grimoirelab-toolkit-git at 9dc821962567715e5358b1192e1b15d8868d2b6c
Traceback (most recent call last):
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/perceval/backends/core/git.py", line 1341, in _exec
    cwd=cwd, env=env)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/worktrees/grimoirelab-toolkit-git': '/tmp/worktrees/grimoirelab-toolkit-git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/graal/graal.py", line 334, in checkout
    self._exec(cmd_checkout, cwd=self.worktreepath, env=self.gitenv)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/perceval/backends/core/git.py", line 1344, in _exec
    raise RepositoryError(cause=str(e))
perceval.errors.RepositoryError: [Errno 2] No such file or directory: '/tmp/worktrees/grimoirelab-toolkit-git': '/tmp/worktrees/grimoirelab-toolkit-git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/grimoire_elk/elk.py", line 171, in feed_backend
    ocean_backend.feed(**params)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/grimoire_elk/raw/elastic.py", line 231, in feed
    self.feed_items(items)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/grimoire_elk/raw/elastic.py", line 247, in feed_items
    for item in items:
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/perceval/backend.py", line 316, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/graal/graal.py", line 197, in fetch_items
    raise e
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/graal/graal.py", line 189, in fetch_items
    self.graalRepo.checkout(commit['commit'])
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/graal/graal.py", line 338, in checkout
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: Impossible to checkout the worktree /tmp/worktrees/grimoirelab-toolkit-git at 9dc821962567715e5358b1192e1b15d8868d2b6c
```

### Environment

```shell
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core
# python -V
Python 3.7.13
# poetry -V
Poetry version 1.1.13
# git log
commit 8a8bb8de7e914b60bdfcbf0c074fda345236c7b2 (HEAD -> master, origin/master, origin/HEAD)
Merge: 77b1d6b 4c50130
Author: Quan Zhou <quan@bitergia.com>
Date:   Tue Mar 29 10:11:21 2022 +0200

    Merge branch 'dynamic' of 'https://github.com/xiao623/grimoirelab-sirmordred'
    
    Merges #534
    Closes #534
```
### Possible solution

Remove the `cocom` backend in the original command.

OR:

1. install `cloc` (In my CentOS 7, run `yum install cloc`). (see [this](https://github.com/chaoss/grimoirelab-graal#how-to-installcreate-the-executables))
2. create two directory `mkdir /tmp/trythis` and `mkdir /tmp/trythis/grimoirelab-toolkit-git`
3. use `mkdir /tmp/trythis` as the `worktree-path` in `setup.cfg`'s `[cocom]` section. (see [this](https://github.com/chaoss/grimoirelab-sirmordred#cocom-))
4. rerun the  `Getting-Started.md` script `python --raw --enrich --cfg ./setup.cfg --backends git cocom`

### Related questions

[#479 ](https://github.com/chaoss/grimoirelab/issues/479) (not in this repo)

I'd like to add some more detail I think is needed to the tutorial file, such as python version, poetry install and etc. But before that let me make sure the removal in this issue is harmless.

**Comment by TieWay59** [comment]
Since there is no feedback for a week, I'm starting to work on it now.

**Comment by zhquan** [comment]
Hi @TieWay59 

Sorry for the late reply have a look at https://github.com/chaoss/grimoirelab/issues/479#issuecomment-1092732486

> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/worktrees/grimoirelab-toolkit-git': '/tmp/worktrees/grimoirelab-toolkit-git'

Change the `worktree-path` to another path and try again, in that example I used `/home/bitergia/worktrees` because the execution was in a Mordred container.

I hope it helps you.

**Comment by TieWay59** [comment]
Thank you @zhquan. In my situation, I'm running it in the *source code and docker* way. So the directory is actually linked to the location in my local machine.

So I will still get the report:

```log
  2022-04-21 19:35:12,321 Error feeding raw from [Errno 2] No such file or directory: '/home/bitergia/worktrees'
```

I tried to create the directory manually, for example, `/tmp/cocom/` and I use this directory in my `setup.cfg` file. And then the report tells me `[Errno 2] No such file or directory: 'cloc': 'cloc'`. I'm really confused about what's going on.

As I investigate deeper into this, I observed that every time I run the project script  `<worktrees-path>/grimoirelab-toolkit-git` would be removed by some process, because I even manually create this folder.

```cmd
$ pwd
/tmp/worktrees/grimoirelab-toolkit-git
# here I run the script `python --raw --enrich --cfg ./setup.cfg --backends git cocom`
$ cd ..
$ ls # here nothing will be print out, grimoirelab-toolkit-git was removed.
```

Below is the full error log after `[Errno 2] No such file or directory: 'cloc': 'cloc'`:

```log
  2022-04-21 19:30:05,398 Analysis failed at 9dc821962567715e5358b1192e1b15d8868d2b6c
  2022-04-21 19:30:05,399 Error feeding raw from cocom (https://github.com/chaoss/grimoirelab-toolkit): [Errno 2] No such file or directory: 'cloc': 'cloc'
Traceback (most recent call last):
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/grimoire_elk/elk.py", line 171, in feed_backend
    ocean_backend.feed(**params)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/grimoire_elk/raw/elastic.py", line 231, in feed
    self.feed_items(items)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/grimoire_elk/raw/elastic.py", line 247, in feed_items
    for item in items:
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/perceval/backend.py", line 316, in fetch
    for item in self.fetch_items(category, **kwargs):
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/graal/graal.py", line 197, in fetch_items
    raise e
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/graal/graal.py", line 190, in fetch_items
    commit['analysis'] = self._analyze(commit)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/graal/backends/core/cocom.py", line 212, in _analyze
    file_info = self.analyzer.analyze(local_path)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/graal/backends/core/cocom.py", line 272, in analyze
    cloc_analysis = self.cloc.analyze(**kwargs)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/site-packages/graal/backends/core/analyzers/cloc.py", line 123, in analyze
    message = subprocess.check_output(cloc_command).decode("utf-8")
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/root/miniconda3/envs/grimoirelab-sirmordred/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'cloc': 'cloc'
```

**Comment by TieWay59** [comment]
Latest progress: I worked around it in a strange way.

> `[Errno 2] No such file or directory: 'cloc': 'cloc'` was caused by my system's lack of cloc install. https://github.com/chaoss/grimoirelab/issues/479#issuecomment-1077439473 inform me to install cloc.

I work around it by this operation sequence:

1. install `cloc` (In my CentOS 7, run `yum install cloc`) which the `Getting-Started.md` didn't inform me to do it.
2. create two directory `mkdir /tmp/trythis` and `mkdir /tmp/trythis/grimoirelab-toolkit-git`
3. use `mkdir /tmp/trythis` as the `worktree-path` in `setup.cfg`'s `[cocom]` section.
4. rerun the  `Getting-Started.md` script `python --raw --enrich --cfg ./setup.cfg --backends git cocom`

I have run and tested it many times, everything works out fine.

Here @zhquan, my new question is, Is there any better way to avoid these manual steps? or shall I add this into the `Getting-Started.md` as a note to help the newcomers in the future?

**Comment by vchrombie** [comment]
Hi @TieWay59, thanks for trying out the different methods and finding the way for yourself.

> Below is the full error log after [Errno 2] No such file or directory: 'cloc': 'cloc':

Yes, this is something people have faced the error and it is reported in the Troubleshooting section too in the Getting-Started.md document. https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#cloc-installation-

> Here @zhquan, my new question is, Is there any better way to avoid these manual steps? or shall I add this into the Getting-Started.md as a note to help the newcomers in the future?

If you find any potential error, you can add it as an entry to the Troubleshooting section. Please feel free to open a PR.

> As @vchrombie suggests, I just remove the cocom backend (see the command above) and leave only git, and this workaround this error fine. And actually, this error doesn't affect the demo result.

Also, I just suggested this to show you that there is nothing wrong with the micro mordred. The setup was working fine, just a small error which is related to cocom backend. You don't have to remove the cocom backend from the documentation because of it.

If your query is done, please feel free to close the issue.

**Comment by TieWay59** [comment]
I will add this example to the Troubleshooting section later and close this issue for now.
It'll be nice if we can find out how this error happens and what's the mechanism behind it. Because it's very annoying to create every not found directory.
Any further discovery would be appreciated, and feel free to reopen this issue again.
