### ISSUE TITLE
AttributeError: '*Enrich' object has no attribute 'roles'

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-sirmordred#627]
We found this error in the `autorefresh` task:
```
sirmordred.task_manager - ERROR - [weblate] Exception in Task Manager 'WeblateEnrich' object has no attribute 'roles'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sirmordred/task_manager.py", line 98, in run
    task.execute()
  File "/usr/local/lib/python3.8/site-packages/sirmordred/task_enrich.py", line 464, in execute
    raise e
  File "/usr/local/lib/python3.8/site-packages/sirmordred/task_enrich.py", line 449, in execute
    self.__autorefresh(self._get_enrich_backend())
  File "/usr/local/lib/python3.8/site-packages/sirmordred/task_enrich.py", line 254, in __autorefresh
    for role in enrich_backend.roles:
AttributeError: 'WeblateEnrich' object has no attribute 'roles'
```

The list of datasources affected by this bug are:

- weblate
- discourse
- hyperkitty
- mattermost
- topicbox
- gitlab-issue
- gitlab-merge
- twitter
- dockerhub
- supybot
- pipermail
- slack
- mediawiki
- stackexchange

**Comment by sduenas** [comment]
Fixed by f5750ba87cfde0f97851a8dc81fd1fb01b4f1f5a
